import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { NextIntlClientProvider } from 'next-intl';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { QrCodeCard } from '@/components/manage/invitations/QrCodeCard';
import type { QrLinkResponseDto } from '@/lib/api/types';
import messages from '@/messages/en.json';

afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
});

function qrLink(overrides: Partial<QrLinkResponseDto>): QrLinkResponseDto {
    return {
        id: 'qr-1',
        eventId: 'event-1',
        token: 'tok',
        publicUrl: 'https://storywall.example/q/tok',
        targetType: 'EVENT_JOIN',
        targetId: null,
        status: 'ACTIVE',
        maxGuests: null,
        label: null,
        labelKey: null,
        metadata: {},
        autoGenerated: false,
        expiresAt: null,
        revokedAt: null,
        createdByUserId: null,
        createdAt: '2026-10-04T00:00:00Z',
        updatedAt: '2026-10-04T00:00:00Z',
        ...overrides,
    } as QrLinkResponseDto;
}

function printedDocument(link: QrLinkResponseDto): string {
    const write = vi.fn();
    vi.spyOn(window, 'open').mockReturnValue({
        document: { write, close: vi.fn() },
        focus: vi.fn(),
        print: vi.fn(),
    } as unknown as Window);
    render(
        <NextIntlClientProvider locale="en" messages={messages}>
            <QrCodeCard qrLink={link} />
        </NextIntlClientProvider>,
    );
    fireEvent.click(screen.getByRole('button', { name: messages.ManagePage.qr.print }));
    return write.mock.calls.map((call) => call[0]).join('');
}

describe('QrCodeCard print', () => {
    // A host names their own links, and the print window shares this page's
    // origin: markup in the name would run there with the host's session.
    it('prints the label as text, never as markup', () => {
        const html = printedDocument(qrLink({ label: '</title><img src=x onerror="alert(1)">' }));

        expect(html).not.toContain('<img');
        expect(html).toContain('&lt;/title&gt;&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');
    });

    it('prints an ordinary label unchanged', () => {
        const html = printedDocument(qrLink({ label: 'Table 4' }));

        expect(html).toContain('<title>Table 4</title>');
        expect(html).toContain('<div class="label">Table 4</div>');
    });
});
