import { AUTH_ERROR_CODES, ERROR_CODES } from '@/lib/api/errors';

type ValueOf<T> = T[keyof T];

export type KnownApiErrorCode = ValueOf<typeof ERROR_CODES> | ValueOf<typeof AUTH_ERROR_CODES>;

export type ApiErrorMessageKey =
    | 'accessDenied'
    | 'accountDeleteAdmin'
    | 'accountDeleteHasHostedEvents'
    | 'accountDeleteOtpExpired'
    | 'accountDeleteOtpInvalid'
    | 'accountDeleteOtpNotRequested'
    | 'accountDeleteOtpTooManyAttempts'
    | 'accountNotActive'
    | 'accountPlansDisabled'
    | 'addonAlreadyActive'
    | 'addonLockedWhileActive'
    | 'addonNotActive'
    | 'alreadyLinked'
    | 'betaFeedbackDisabled'
    | 'authenticationRequired'
    | 'checkoutAmountBelowMinimum'
    | 'checkoutSessionUnresolved'
    | 'coHostInviteNotYours'
    | 'coHostInvitationAlreadyPending'
    | 'coHostInvitationsPendingLimit'
    | 'collaborationAlreadyRedeemed'
    | 'collaborationCodeNotValid'
    | 'collaborationEarningNotPayable'
    | 'concurrentModification'
    | 'conflict'
    | 'coverageEnded'
    | 'coverageOptionDuplicate'
    | 'coverageOptionInvalid'
    | 'coverageOptionLastInitial'
    | 'coverageOptionUnavailable'
    | 'discountNotApplicableToUpgrade'
    | 'duplicateMediaIdInRequest'
    | 'duplicateMembership'
    | 'duplicateReaction'
    | 'emailAlreadyExists'
    | 'eventDatesIncomplete'
    | 'eventStartPassed'
    | 'eventStartTooFarAhead'
    | 'eventCreationLocked'
    | 'eventDraftLimitReached'
    | 'eventDeleteAlreadyPending'
    | 'eventDeleteNotPrimaryHost'
    | 'eventDeleteOtpExpired'
    | 'eventDeleteOtpInvalid'
    | 'eventDeleteOtpNotRequested'
    | 'eventDeleteOtpTooManyAttempts'
    | 'eventWithdrawn'
    | 'eventHostDisplayOrderReserved'
    | 'eventHostPrimaryCannotBeRemoved'
    | 'eventHostTransferNotPrimaryHost'
    | 'hostTransferWithdrawalOpen'
    | 'eventNotActive'
    | 'eventNotDraft'
    | 'eventModuleCompositionLocked'
    | 'eventVisibilityNotSupported'
    | 'eventTypeNotAvailable'
    | 'eventSessionScheduleLocked'
    | 'eventSessionMainDatesReadOnly'
    | 'eventSessionMainLocationReadOnly'
    | 'eventSessionSecondaryAlreadyAssigned'
    | 'eventSessionLimitReached'
    | 'eventSessionMainNotDeletable'
    | 'eventSessionMainAlreadyExists'
    | 'eventCoHostLimitExceeded'
    | 'invalidEventType'
    | 'invalidPlanTierScope'
    | 'forbidden'
    | 'giftAlreadyClaimed'
    | 'giftCardLocked'
    | 'giftClaimNotAllowed'
    | 'giftClaimPinInvalid'
    | 'giftEventNotActive'
    | 'giftHandoverPending'
    | 'giftNotAvailableOnPlan'
    | 'giftNotPrimaryHost'
    | 'giftAccountNotPrimaryHost'
    | 'giftOrderNotYours'
    | 'giftRecipientProtected'
    | 'guidelinesAcceptanceRequired'
    | 'guidelinesVersionMismatch'
    | 'signupAcceptanceRequired'
    | 'termsAcceptanceRequired'
    | 'termsVersionMismatch'
    | 'internalError'
    | 'invalidCredentials'
    | 'invalidIban'
    | 'invalidRefreshToken'
    | 'invitationExhausted'
    | 'invitationExpired'
    | 'invitationNotFound'
    | 'malformedRequestBody'
    | 'mediaFileCorrupt'
    | 'mediaFileTooLarge'
    | 'mediaArchivePartNotFound'
    | 'mediaArchiveSelectionEmpty'
    | 'mediaArchiveSelectionTooLarge'
    | 'mediaArchiveSelectionInvalid'
    | 'mediaArchiveDownloadsInProgress'
    | 'mediaArchiveDailyLimitReached'
    | 'mediaImageTooManyPixels'
    | 'mediaProcessingBusy'
    | 'methodNotAllowed'
    | 'memberLimit'
    | 'moduleUnavailable'
    | 'qrMediaUploadDisabled'
    | 'qrUploadAcceptanceRequired'
    | 'oauthTokenInvalid'
    | 'oauthEmailRequired'
    | 'qrLinkNotAvailable'
    | 'qrSharedLinkHostManaged'
    | 'orderNotManual'
    | 'moderationDecisionInvalid'
    | 'eventBanned'
    | 'eventSuspended'
    | 'eventAlreadySuspended'
    | 'eventNotSuspended'
    | 'eventAlreadyClosed'
    | 'moderationCaseClosed'
    | 'noticeAlreadyHandled'
    | 'moderationMemberIsHost'
    | 'moderationTargetProtected'
    | 'orderNotPending'
    | 'planCurrencyMismatch'
    | 'planCurrencyUnsupported'
    | 'planInUse'
    | 'planIsOnlyDefault'
    | 'planNotAnUpgrade'
    | 'planNotPriced'
    | 'purchaseNotPrimaryHost'
    | 'purchaseWithdrawalOpen'
    | 'planNotPurchasable'
    | 'planTierNotAvailableForEventType'
    | 'postMediaLimitExceeded'
    | 'postPinNotHost'
    | 'postEditNotAuthor'
    | 'announcementNotHost'
    | 'storyExpiryOutOfRange'
    | 'storyLiveLimitReached'
    | 'storyMediaAlreadyLive'
    | 'themeFontInvalidFile'
    | 'themeFontKeyTaken'
    | 'themeFontMissingCharacters'
    | 'themeFontNotAssignable'
    | 'themeFontTooLarge'
    | 'themePresetNotSelectable'
    | 'themeTitleColorLowContrast'
    | 'eventEnded'
    | 'eventScheduleLocked'
    | 'paidServiceCurrencyMismatch'
    | 'paidServiceInUse'
    | 'paidServiceNotOnPlan'
    | 'paidServiceNotPurchasable'
    | 'invalidPaidServiceKind'
    | 'qrLinkNotFound'
    | 'rateLimited'
    | 'reportOwnContent'
    | 'sessionRsvpNotEnabled'
    | 'reactionTypeInUse'
    | 'reactionTypeLimitExceeded'
    | 'reactionTypeNotUsable'
    | 'resourceNotFound'
    | 'resourceBusy'
    | 'rsvpNotAttending'
    | 'storageLimit'
    | 'storageUploadFailed'
    | 'requestTooLarge'
    | 'unsupportedMediaFormat'
    | 'tooManyFiles'
    | 'validationFailed'
    | 'webhookAlreadyProcessed'
    | 'webhookNotReplayable'
    | 'webhookPayloadTooLarge'
    | 'withdrawalTermsVersionStale'
    | 'withdrawalRefused'
    | 'withdrawalNotHeld'
    | 'withdrawalOrderDisputed'
    | 'withdrawalKeepEventDayNotDue'
    | 'withdrawalOrderKindNotSupported'
    | 'withdrawalConfirmationInvalid'
    | 'withdrawalPreviewStale'
    | 'demoEventLocked'
    | 'demoActAsRefused'
    | 'demoDesignationInvalid'
    | 'demoPersonaAvatarRefused'
    | 'memberRoleInvalid'
    | 'memberRoleUnknown'
    | 'memberRoleCustomBlocked'
    | 'memberRoleCustomNotAllowed'
    | 'memberRoleCustomLocked'
    | 'memberRoleHostOnly'
    | 'memberRoleFeaturedMember'
    | 'memberRoleCapReached'
    | 'memberRoleTextChanged'
    | 'withdrawalNotPrimaryHost'
    | 'oauthEmailUnverified';

export const API_ERROR_MESSAGE_KEYS = {
    [AUTH_ERROR_CODES.ACCESS_DENIED]: 'accessDenied',
    [AUTH_ERROR_CODES.AUTHENTICATION_REQUIRED]: 'authenticationRequired',
    [ERROR_CODES.ACCOUNT_NOT_ACTIVE]: 'accountNotActive',
    [ERROR_CODES.OAUTH_TOKEN_INVALID]: 'oauthTokenInvalid',
    [ERROR_CODES.OAUTH_EMAIL_REQUIRED]: 'oauthEmailRequired',
    [ERROR_CODES.OAUTH_EMAIL_UNVERIFIED]: 'oauthEmailUnverified',
    [ERROR_CODES.ACCOUNT_PLANS_DISABLED]: 'accountPlansDisabled',
    [ERROR_CODES.ADDON_ALREADY_ACTIVE]: 'addonAlreadyActive',
    [ERROR_CODES.ADDON_LOCKED_WHILE_ACTIVE]: 'addonLockedWhileActive',
    [ERROR_CODES.ADDON_NOT_ACTIVE]: 'addonNotActive',
    [ERROR_CODES.ALREADY_LINKED]: 'alreadyLinked',
    [ERROR_CODES.CHECKOUT_AMOUNT_BELOW_MINIMUM]: 'checkoutAmountBelowMinimum',
    [ERROR_CODES.CHECKOUT_SESSION_UNRESOLVED]: 'checkoutSessionUnresolved',
    [ERROR_CODES.CO_HOST_INVITE_NOT_YOURS]: 'coHostInviteNotYours',
    [ERROR_CODES.CO_HOST_INVITATION_ALREADY_PENDING]: 'coHostInvitationAlreadyPending',
    [ERROR_CODES.CO_HOST_INVITATIONS_PENDING_LIMIT]: 'coHostInvitationsPendingLimit',
    [ERROR_CODES.COLLABORATION_ALREADY_REDEEMED]: 'collaborationAlreadyRedeemed',
    [ERROR_CODES.COLLABORATION_CODE_NOT_VALID]: 'collaborationCodeNotValid',
    [ERROR_CODES.COLLABORATION_EARNING_NOT_PAYABLE]: 'collaborationEarningNotPayable',
    [ERROR_CODES.CONFLICT]: 'conflict',
    [ERROR_CODES.CONCURRENT_MODIFICATION]: 'concurrentModification',
    [ERROR_CODES.COVERAGE_ENDED]: 'coverageEnded',
    [ERROR_CODES.COVERAGE_OPTION_DUPLICATE]: 'coverageOptionDuplicate',
    [ERROR_CODES.COVERAGE_OPTION_INVALID]: 'coverageOptionInvalid',
    [ERROR_CODES.COVERAGE_OPTION_LAST_INITIAL]: 'coverageOptionLastInitial',
    [ERROR_CODES.COVERAGE_OPTION_UNAVAILABLE]: 'coverageOptionUnavailable',
    [ERROR_CODES.DISCOUNT_NOT_APPLICABLE_TO_UPGRADE]: 'discountNotApplicableToUpgrade',
    [ERROR_CODES.DUPLICATE_MEDIA_ID_IN_REQUEST]: 'duplicateMediaIdInRequest',
    [ERROR_CODES.DUPLICATE_MEMBERSHIP]: 'duplicateMembership',
    [ERROR_CODES.DUPLICATE_REACTION]: 'duplicateReaction',
    [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'emailAlreadyExists',
    [ERROR_CODES.EVENT_DATES_INCOMPLETE]: 'eventDatesIncomplete',
    [ERROR_CODES.EVENT_START_PASSED]: 'eventStartPassed',
    [ERROR_CODES.EVENT_START_TOO_FAR_AHEAD]: 'eventStartTooFarAhead',
    [ERROR_CODES.EVENT_CREATION_LOCKED]: 'eventCreationLocked',
    [ERROR_CODES.EVENT_DRAFT_LIMIT_REACHED]: 'eventDraftLimitReached',
    [ERROR_CODES.EVENT_DELETE_ALREADY_PENDING]: 'eventDeleteAlreadyPending',
    [ERROR_CODES.EVENT_DELETE_NOT_PRIMARY_HOST]: 'eventDeleteNotPrimaryHost',
    [ERROR_CODES.EVENT_DELETE_OTP_EXPIRED]: 'eventDeleteOtpExpired',
    [ERROR_CODES.EVENT_DELETE_OTP_INVALID]: 'eventDeleteOtpInvalid',
    [ERROR_CODES.EVENT_DELETE_OTP_NOT_REQUESTED]: 'eventDeleteOtpNotRequested',
    [ERROR_CODES.EVENT_DELETE_OTP_TOO_MANY_ATTEMPTS]: 'eventDeleteOtpTooManyAttempts',
    [ERROR_CODES.EVENT_WITHDRAWN]: 'eventWithdrawn',
    [ERROR_CODES.EVENT_HOST_DISPLAY_ORDER_RESERVED]: 'eventHostDisplayOrderReserved',
    [ERROR_CODES.EVENT_HOST_PRIMARY_CANNOT_BE_REMOVED]: 'eventHostPrimaryCannotBeRemoved',
    [ERROR_CODES.EVENT_HOST_TRANSFER_NOT_PRIMARY_HOST]: 'eventHostTransferNotPrimaryHost',
    [ERROR_CODES.HOST_TRANSFER_WITHDRAWAL_OPEN]: 'hostTransferWithdrawalOpen',
    [ERROR_CODES.WITHDRAWAL_NOT_PRIMARY_HOST]: 'withdrawalNotPrimaryHost',
    [ERROR_CODES.EVENT_MEMBER_LIMIT_EXCEEDED]: 'memberLimit',
    [ERROR_CODES.EVENT_NOT_ACTIVE]: 'eventNotActive',
    [ERROR_CODES.EVENT_NOT_DRAFT]: 'eventNotDraft',
    [ERROR_CODES.EVENT_MODULE_COMPOSITION_LOCKED]: 'eventModuleCompositionLocked',
    [ERROR_CODES.EVENT_VISIBILITY_NOT_SUPPORTED]: 'eventVisibilityNotSupported',
    [ERROR_CODES.EVENT_TYPE_NOT_AVAILABLE]: 'eventTypeNotAvailable',
    [ERROR_CODES.EVENT_SESSION_SCHEDULE_LOCKED]: 'eventSessionScheduleLocked',
    [ERROR_CODES.EVENT_SESSION_MAIN_DATES_READ_ONLY]: 'eventSessionMainDatesReadOnly',
    [ERROR_CODES.EVENT_SESSION_MAIN_LOCATION_READ_ONLY]: 'eventSessionMainLocationReadOnly',
    [ERROR_CODES.EVENT_SESSION_SECONDARY_ALREADY_ASSIGNED]: 'eventSessionSecondaryAlreadyAssigned',
    [ERROR_CODES.EVENT_SESSION_LIMIT_REACHED]: 'eventSessionLimitReached',
    [ERROR_CODES.EVENT_SESSION_MAIN_NOT_DELETABLE]: 'eventSessionMainNotDeletable',
    [ERROR_CODES.EVENT_SESSION_MAIN_ALREADY_EXISTS]: 'eventSessionMainAlreadyExists',
    [ERROR_CODES.ACCOUNT_DELETE_OTP_NOT_REQUESTED]: 'accountDeleteOtpNotRequested',
    [ERROR_CODES.ACCOUNT_DELETE_OTP_EXPIRED]: 'accountDeleteOtpExpired',
    [ERROR_CODES.ACCOUNT_DELETE_OTP_TOO_MANY_ATTEMPTS]: 'accountDeleteOtpTooManyAttempts',
    [ERROR_CODES.ACCOUNT_DELETE_OTP_INVALID]: 'accountDeleteOtpInvalid',
    [ERROR_CODES.ACCOUNT_DELETE_ADMIN]: 'accountDeleteAdmin',
    [ERROR_CODES.ACCOUNT_DELETE_HAS_HOSTED_EVENTS]: 'accountDeleteHasHostedEvents',
    [ERROR_CODES.QR_UPLOAD_ACCEPTANCE_REQUIRED]: 'qrUploadAcceptanceRequired',
    [ERROR_CODES.POST_EDIT_NOT_AUTHOR]: 'postEditNotAuthor',
    [ERROR_CODES.EVENT_CO_HOST_LIMIT_EXCEEDED]: 'eventCoHostLimitExceeded',
    [ERROR_CODES.INVALID_EVENT_TYPE]: 'invalidEventType',
    [ERROR_CODES.EVENT_STORAGE_LIMIT_EXCEEDED]: 'storageLimit',
    [ERROR_CODES.FORBIDDEN]: 'forbidden',
    [ERROR_CODES.GIFT_CLAIM_PIN_INVALID]: 'giftClaimPinInvalid',
    [ERROR_CODES.GIFT_CLAIM_NOT_ALLOWED]: 'giftClaimNotAllowed',
    [ERROR_CODES.GIFT_ORDER_NOT_YOURS]: 'giftOrderNotYours',
    [ERROR_CODES.GIFT_NOT_PRIMARY_HOST]: 'giftNotPrimaryHost',
    [ERROR_CODES.GIFT_ACCOUNT_NOT_PRIMARY_HOST]: 'giftAccountNotPrimaryHost',
    [ERROR_CODES.GIFT_RECIPIENT_PROTECTED]: 'giftRecipientProtected',
    [ERROR_CODES.GIFT_NOT_AVAILABLE_ON_PLAN]: 'giftNotAvailableOnPlan',
    [ERROR_CODES.GIFT_ALREADY_CLAIMED]: 'giftAlreadyClaimed',
    [ERROR_CODES.GIFT_CARD_LOCKED]: 'giftCardLocked',
    [ERROR_CODES.GIFT_EVENT_NOT_ACTIVE]: 'giftEventNotActive',
    [ERROR_CODES.GIFT_HANDOVER_PENDING]: 'giftHandoverPending',
    [ERROR_CODES.GUIDELINES_VERSION_MISMATCH]: 'guidelinesVersionMismatch',
    [ERROR_CODES.GUIDELINES_ACCEPTANCE_REQUIRED]: 'guidelinesAcceptanceRequired',
    [ERROR_CODES.TERMS_VERSION_MISMATCH]: 'termsVersionMismatch',
    [ERROR_CODES.SIGNUP_ACCEPTANCE_REQUIRED]: 'signupAcceptanceRequired',
    [ERROR_CODES.TERMS_ACCEPTANCE_REQUIRED]: 'termsAcceptanceRequired',
    [ERROR_CODES.INTERNAL_ERROR]: 'internalError',
    [ERROR_CODES.INVALID_CREDENTIALS]: 'invalidCredentials',
    [ERROR_CODES.INVALID_IBAN]: 'invalidIban',
    [ERROR_CODES.INVALID_REFRESH_TOKEN]: 'invalidRefreshToken',
    [ERROR_CODES.INVITATION_EXHAUSTED]: 'invitationExhausted',
    [ERROR_CODES.INVITATION_EXPIRED]: 'invitationExpired',
    [ERROR_CODES.INVITATION_NOT_FOUND]: 'invitationNotFound',
    [ERROR_CODES.MALFORMED_REQUEST_BODY]: 'malformedRequestBody',
    [ERROR_CODES.MEDIA_FILE_CORRUPT]: 'mediaFileCorrupt',
    [ERROR_CODES.MEDIA_FILE_TOO_LARGE]: 'mediaFileTooLarge',
    [ERROR_CODES.MEDIA_ARCHIVE_PART_NOT_FOUND]: 'mediaArchivePartNotFound',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_EMPTY]: 'mediaArchiveSelectionEmpty',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_TOO_LARGE]: 'mediaArchiveSelectionTooLarge',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_INVALID]: 'mediaArchiveSelectionInvalid',
    [ERROR_CODES.MEDIA_ARCHIVE_DOWNLOADS_IN_PROGRESS]: 'mediaArchiveDownloadsInProgress',
    [ERROR_CODES.MEDIA_ARCHIVE_DAILY_LIMIT_REACHED]: 'mediaArchiveDailyLimitReached',
    [ERROR_CODES.MEDIA_IMAGE_TOO_MANY_PIXELS]: 'mediaImageTooManyPixels',
    [ERROR_CODES.MEDIA_PROCESSING_BUSY]: 'mediaProcessingBusy',
    [ERROR_CODES.METHOD_NOT_ALLOWED]: 'methodNotAllowed',
    [ERROR_CODES.INVALID_PAID_SERVICE_KIND]: 'invalidPaidServiceKind',
    [ERROR_CODES.MODULE_NOT_AVAILABLE]: 'moduleUnavailable',
    [ERROR_CODES.QR_MEDIA_UPLOAD_DISABLED]: 'qrMediaUploadDisabled',
    [ERROR_CODES.ORDER_NOT_PENDING]: 'orderNotPending',
    [ERROR_CODES.ORDER_NOT_MANUAL]: 'orderNotManual',
    [ERROR_CODES.MODERATION_DECISION_INVALID]: 'moderationDecisionInvalid',
    [ERROR_CODES.EVENT_BANNED]: 'eventBanned',
    [ERROR_CODES.EVENT_SUSPENDED]: 'eventSuspended',
    [ERROR_CODES.EVENT_ALREADY_SUSPENDED]: 'eventAlreadySuspended',
    [ERROR_CODES.EVENT_NOT_SUSPENDED]: 'eventNotSuspended',
    [ERROR_CODES.EVENT_ALREADY_CLOSED]: 'eventAlreadyClosed',
    [ERROR_CODES.MODERATION_CASE_CLOSED]: 'moderationCaseClosed',
    [ERROR_CODES.NOTICE_ALREADY_HANDLED]: 'noticeAlreadyHandled',
    [ERROR_CODES.MODERATION_MEMBER_IS_HOST]: 'moderationMemberIsHost',
    [ERROR_CODES.MODERATION_TARGET_PROTECTED]: 'moderationTargetProtected',
    [ERROR_CODES.PLAN_TIER_CURRENCY_MISMATCH]: 'planCurrencyMismatch',
    [ERROR_CODES.PLAN_TIER_CURRENCY_UNSUPPORTED]: 'planCurrencyUnsupported',
    [ERROR_CODES.PLAN_TIER_IN_USE]: 'planInUse',
    [ERROR_CODES.PLAN_TIER_IS_ONLY_DEFAULT]: 'planIsOnlyDefault',
    [ERROR_CODES.PLAN_TIER_NOT_AN_UPGRADE]: 'planNotAnUpgrade',
    [ERROR_CODES.PLAN_TIER_NOT_PRICED]: 'planNotPriced',
    [ERROR_CODES.PURCHASE_NOT_PRIMARY_HOST]: 'purchaseNotPrimaryHost',
    [ERROR_CODES.PURCHASE_WITHDRAWAL_OPEN]: 'purchaseWithdrawalOpen',
    [ERROR_CODES.PLAN_TIER_NOT_PURCHASABLE]: 'planNotPurchasable',
    [ERROR_CODES.PLAN_TIER_NOT_AVAILABLE_FOR_EVENT_TYPE]: 'planTierNotAvailableForEventType',
    [ERROR_CODES.POST_MEDIA_LIMIT_EXCEEDED]: 'postMediaLimitExceeded',
    [ERROR_CODES.POST_PIN_NOT_HOST]: 'postPinNotHost',
    [ERROR_CODES.ANNOUNCEMENT_NOT_HOST]: 'announcementNotHost',
    [ERROR_CODES.STORY_EXPIRY_OUT_OF_RANGE]: 'storyExpiryOutOfRange',
    [ERROR_CODES.STORY_LIVE_LIMIT_REACHED]: 'storyLiveLimitReached',
    [ERROR_CODES.STORY_MEDIA_ALREADY_LIVE]: 'storyMediaAlreadyLive',
    [ERROR_CODES.THEME_PRESET_NOT_SELECTABLE]: 'themePresetNotSelectable',
    [ERROR_CODES.THEME_FONT_INVALID_FILE]: 'themeFontInvalidFile',
    [ERROR_CODES.THEME_FONT_TOO_LARGE]: 'themeFontTooLarge',
    [ERROR_CODES.THEME_FONT_MISSING_CHARACTERS]: 'themeFontMissingCharacters',
    [ERROR_CODES.THEME_TITLE_COLOR_LOW_CONTRAST]: 'themeTitleColorLowContrast',
    [ERROR_CODES.THEME_FONT_NOT_ASSIGNABLE]: 'themeFontNotAssignable',
    [ERROR_CODES.THEME_FONT_KEY_TAKEN]: 'themeFontKeyTaken',
    [ERROR_CODES.EVENT_ENDED]: 'eventEnded',
    [ERROR_CODES.PAID_SERVICE_CURRENCY_MISMATCH]: 'paidServiceCurrencyMismatch',
    [ERROR_CODES.PAID_SERVICE_IN_USE]: 'paidServiceInUse',
    [ERROR_CODES.PAID_SERVICE_NOT_ON_PLAN]: 'paidServiceNotOnPlan',
    [ERROR_CODES.PAID_SERVICE_NOT_PURCHASABLE]: 'paidServiceNotPurchasable',
    [ERROR_CODES.QR_LINK_NOT_FOUND]: 'qrLinkNotFound',
    [ERROR_CODES.QR_LINK_NOT_AVAILABLE]: 'qrLinkNotAvailable',
    [ERROR_CODES.QR_SHARED_LINK_HOST_MANAGED]: 'qrSharedLinkHostManaged',
    [ERROR_CODES.RATE_LIMITED]: 'rateLimited',
    [ERROR_CODES.REPORT_OWN_CONTENT]: 'reportOwnContent',
    [ERROR_CODES.SESSION_RSVP_NOT_ENABLED]: 'sessionRsvpNotEnabled',
    [ERROR_CODES.RSVP_NOT_ATTENDING]: 'rsvpNotAttending',
    [ERROR_CODES.BETA_FEEDBACK_DISABLED]: 'betaFeedbackDisabled',
    [ERROR_CODES.EVENT_SCHEDULE_LOCKED]: 'eventScheduleLocked',
    [ERROR_CODES.REACTION_TYPE_IN_USE]: 'reactionTypeInUse',
    [ERROR_CODES.REACTION_TYPE_LIMIT_EXCEEDED]: 'reactionTypeLimitExceeded',
    [ERROR_CODES.REACTION_TYPE_NOT_USABLE]: 'reactionTypeNotUsable',
    [ERROR_CODES.RESOURCE_NOT_FOUND]: 'resourceNotFound',
    [ERROR_CODES.RESOURCE_BUSY]: 'resourceBusy',
    [ERROR_CODES.STORAGE_UPLOAD_FAILED]: 'storageUploadFailed',
    [ERROR_CODES.REQUEST_TOO_LARGE]: 'requestTooLarge',
    [ERROR_CODES.UNSUPPORTED_MEDIA_FORMAT]: 'unsupportedMediaFormat',
    [ERROR_CODES.TOO_MANY_FILES]: 'tooManyFiles',
    [ERROR_CODES.VALIDATION_FAILED]: 'validationFailed',
    [ERROR_CODES.INVALID_PLAN_TIER_SCOPE]: 'invalidPlanTierScope',
    [ERROR_CODES.WEBHOOK_ALREADY_PROCESSED]: 'webhookAlreadyProcessed',
    [ERROR_CODES.WEBHOOK_NOT_REPLAYABLE]: 'webhookNotReplayable',
    [ERROR_CODES.WEBHOOK_PAYLOAD_TOO_LARGE]: 'webhookPayloadTooLarge',
    [ERROR_CODES.WITHDRAWAL_TERMS_VERSION_STALE]: 'withdrawalTermsVersionStale',
    [ERROR_CODES.WITHDRAWAL_REFUSED]: 'withdrawalRefused',
    [ERROR_CODES.WITHDRAWAL_NOT_HELD]: 'withdrawalNotHeld',
    [ERROR_CODES.WITHDRAWAL_ORDER_DISPUTED]: 'withdrawalOrderDisputed',
    [ERROR_CODES.WITHDRAWAL_KEEP_EVENT_DAY_NOT_DUE]: 'withdrawalKeepEventDayNotDue',
    [ERROR_CODES.WITHDRAWAL_ORDER_KIND_NOT_SUPPORTED]: 'withdrawalOrderKindNotSupported',
    [ERROR_CODES.WITHDRAWAL_CONFIRMATION_INVALID]: 'withdrawalConfirmationInvalid',
    [ERROR_CODES.WITHDRAWAL_PREVIEW_STALE]: 'withdrawalPreviewStale',
    [ERROR_CODES.DEMO_EVENT_LOCKED]: 'demoEventLocked',
    [ERROR_CODES.DEMO_ACT_AS_REFUSED]: 'demoActAsRefused',
    [ERROR_CODES.DEMO_DESIGNATION_INVALID]: 'demoDesignationInvalid',
    [ERROR_CODES.DEMO_PERSONA_AVATAR_REFUSED]: 'demoPersonaAvatarRefused',
    [ERROR_CODES.MEMBER_ROLE_INVALID_REQUEST]: 'memberRoleInvalid',
    [ERROR_CODES.MEMBER_ROLE_UNKNOWN]: 'memberRoleUnknown',
    [ERROR_CODES.MEMBER_ROLE_CUSTOM_BLOCKED]: 'memberRoleCustomBlocked',
    [ERROR_CODES.MEMBER_ROLE_CUSTOM_NOT_ALLOWED]: 'memberRoleCustomNotAllowed',
    [ERROR_CODES.MEMBER_ROLE_CUSTOM_LOCKED]: 'memberRoleCustomLocked',
    [ERROR_CODES.MEMBER_ROLE_HOST_ONLY]: 'memberRoleHostOnly',
    [ERROR_CODES.MEMBER_ROLE_FEATURED_MEMBER]: 'memberRoleFeaturedMember',
    [ERROR_CODES.MEMBER_ROLE_CAP_REACHED]: 'memberRoleCapReached',
    [ERROR_CODES.MEMBER_ROLE_TEXT_CHANGED]: 'memberRoleTextChanged',
} satisfies Record<KnownApiErrorCode, ApiErrorMessageKey>;

export function getApiErrorMessageKey(code: number | string | undefined): ApiErrorMessageKey | undefined {
    return API_ERROR_MESSAGE_KEYS[code as KnownApiErrorCode];
}
