import { AUTH_ERROR_CODES, ERROR_CODES } from '@/lib/api/errors';

type ValueOf<T> = T[keyof T];

export type KnownApiErrorCode = ValueOf<typeof ERROR_CODES> | ValueOf<typeof AUTH_ERROR_CODES>;

export type ApiErrorMessageKey =
    | 'accessDenied'
    | 'accountNotActive'
    | 'accountPlansDisabled'
    | 'addonAlreadyActive'
    | 'addonLockedWhileActive'
    | 'addonNotActive'
    | 'alreadyLinked'
    | 'authenticationRequired'
    | 'checkoutAmountBelowMinimum'
    | 'checkoutSessionUnresolved'
    | 'coHostInviteNotYours'
    | 'collaborationAlreadyRedeemed'
    | 'collaborationCodeNotValid'
    | 'collaborationEarningNotPayable'
    | 'conflict'
    | 'duplicateMediaIdInRequest'
    | 'duplicateMembership'
    | 'duplicateReaction'
    | 'emailAlreadyExists'
    | 'eventDatesIncomplete'
    | 'eventDeleteAlreadyPending'
    | 'eventDeleteNotPrimaryHost'
    | 'eventNotActive'
    | 'eventNotDraft'
    | 'eventModuleCompositionLocked'
    | 'eventVisibilityNotSupported'
    | 'eventTypeNotAvailable'
    | 'eventSessionScheduleLocked'
    | 'eventSessionMainDatesReadOnly'
    | 'eventSessionSecondaryAlreadyAssigned'
    | 'invalidEventType'
    | 'invalidPlanTierScope'
    | 'forbidden'
    | 'internalError'
    | 'invalidCredentials'
    | 'invalidIban'
    | 'invalidRefreshToken'
    | 'invitationExhausted'
    | 'invitationExpired'
    | 'invitationNotFound'
    | 'malformedRequestBody'
    | 'mediaFileCorrupt'
    | 'mediaFileTooLarge'
    | 'mediaArchivePartNotFound'
    | 'mediaArchiveSelectionEmpty'
    | 'mediaArchiveSelectionTooLarge'
    | 'mediaArchiveSelectionInvalid'
    | 'mediaImageTooManyPixels'
    | 'mediaProcessingBusy'
    | 'methodNotAllowed'
    | 'memberLimit'
    | 'moduleUnavailable'
    | 'orderNotPending'
    | 'orderNotRefundable'
    | 'planCurrencyMismatch'
    | 'planCurrencyUnsupported'
    | 'planInUse'
    | 'planIsOnlyDefault'
    | 'planNotAnUpgrade'
    | 'planNotPriced'
    | 'planNotPurchasable'
    | 'planTierNotAvailableForEventType'
    | 'postMediaLimitExceeded'
    | 'eventScheduleLocked'
    | 'paidServiceCurrencyMismatch'
    | 'paidServiceInUse'
    | 'paidServiceNotOnPlan'
    | 'paidServiceNotPurchasable'
    | 'invalidPaidServiceKind'
    | 'qrLinkNotFound'
    | 'rateLimited'
    | 'refundAlreadyRequested'
    | 'refundNotEligible'
    | 'refundNotPending'
    | 'reactionTypeInUse'
    | 'reactionTypeLimitExceeded'
    | 'reactionTypeNotUsable'
    | 'resourceNotFound'
    | 'storageLimit'
    | 'storageUploadFailed'
    | 'originalsAddonNotActive'
    | 'requestTooLarge'
    | 'unsupportedMediaFormat'
    | 'tooManyFiles'
    | 'validationFailed'
    | 'webhookAlreadyProcessed'
    | 'webhookNotReplayable'
    | 'webhookPayloadTooLarge';

export const API_ERROR_MESSAGE_KEYS = {
    [AUTH_ERROR_CODES.ACCESS_DENIED]: 'accessDenied',
    [AUTH_ERROR_CODES.AUTHENTICATION_REQUIRED]: 'authenticationRequired',
    [ERROR_CODES.ACCOUNT_NOT_ACTIVE]: 'accountNotActive',
    [ERROR_CODES.ACCOUNT_PLANS_DISABLED]: 'accountPlansDisabled',
    [ERROR_CODES.ADDON_ALREADY_ACTIVE]: 'addonAlreadyActive',
    [ERROR_CODES.ADDON_LOCKED_WHILE_ACTIVE]: 'addonLockedWhileActive',
    [ERROR_CODES.ADDON_NOT_ACTIVE]: 'addonNotActive',
    [ERROR_CODES.ALREADY_LINKED]: 'alreadyLinked',
    [ERROR_CODES.CHECKOUT_AMOUNT_BELOW_MINIMUM]: 'checkoutAmountBelowMinimum',
    [ERROR_CODES.CHECKOUT_SESSION_UNRESOLVED]: 'checkoutSessionUnresolved',
    [ERROR_CODES.CO_HOST_INVITE_NOT_YOURS]: 'coHostInviteNotYours',
    [ERROR_CODES.COLLABORATION_ALREADY_REDEEMED]: 'collaborationAlreadyRedeemed',
    [ERROR_CODES.COLLABORATION_CODE_NOT_VALID]: 'collaborationCodeNotValid',
    [ERROR_CODES.COLLABORATION_EARNING_NOT_PAYABLE]: 'collaborationEarningNotPayable',
    [ERROR_CODES.CONFLICT]: 'conflict',
    [ERROR_CODES.DUPLICATE_MEDIA_ID_IN_REQUEST]: 'duplicateMediaIdInRequest',
    [ERROR_CODES.DUPLICATE_MEMBERSHIP]: 'duplicateMembership',
    [ERROR_CODES.DUPLICATE_REACTION]: 'duplicateReaction',
    [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'emailAlreadyExists',
    [ERROR_CODES.EVENT_DATES_INCOMPLETE]: 'eventDatesIncomplete',
    [ERROR_CODES.EVENT_DELETE_ALREADY_PENDING]: 'eventDeleteAlreadyPending',
    [ERROR_CODES.EVENT_DELETE_NOT_PRIMARY_HOST]: 'eventDeleteNotPrimaryHost',
    [ERROR_CODES.EVENT_MEMBER_LIMIT_EXCEEDED]: 'memberLimit',
    [ERROR_CODES.EVENT_NOT_ACTIVE]: 'eventNotActive',
    [ERROR_CODES.EVENT_NOT_DRAFT]: 'eventNotDraft',
    [ERROR_CODES.EVENT_MODULE_COMPOSITION_LOCKED]: 'eventModuleCompositionLocked',
    [ERROR_CODES.EVENT_VISIBILITY_NOT_SUPPORTED]: 'eventVisibilityNotSupported',
    [ERROR_CODES.EVENT_TYPE_NOT_AVAILABLE]: 'eventTypeNotAvailable',
    [ERROR_CODES.EVENT_SESSION_SCHEDULE_LOCKED]: 'eventSessionScheduleLocked',
    [ERROR_CODES.EVENT_SESSION_MAIN_DATES_READ_ONLY]: 'eventSessionMainDatesReadOnly',
    [ERROR_CODES.EVENT_SESSION_SECONDARY_ALREADY_ASSIGNED]: 'eventSessionSecondaryAlreadyAssigned',
    [ERROR_CODES.INVALID_EVENT_TYPE]: 'invalidEventType',
    [ERROR_CODES.EVENT_STORAGE_LIMIT_EXCEEDED]: 'storageLimit',
    [ERROR_CODES.FORBIDDEN]: 'forbidden',
    [ERROR_CODES.INTERNAL_ERROR]: 'internalError',
    [ERROR_CODES.INVALID_CREDENTIALS]: 'invalidCredentials',
    [ERROR_CODES.INVALID_IBAN]: 'invalidIban',
    [ERROR_CODES.INVALID_REFRESH_TOKEN]: 'invalidRefreshToken',
    [ERROR_CODES.INVITATION_EXHAUSTED]: 'invitationExhausted',
    [ERROR_CODES.INVITATION_EXPIRED]: 'invitationExpired',
    [ERROR_CODES.INVITATION_NOT_FOUND]: 'invitationNotFound',
    [ERROR_CODES.MALFORMED_REQUEST_BODY]: 'malformedRequestBody',
    [ERROR_CODES.MEDIA_FILE_CORRUPT]: 'mediaFileCorrupt',
    [ERROR_CODES.MEDIA_FILE_TOO_LARGE]: 'mediaFileTooLarge',
    [ERROR_CODES.MEDIA_ARCHIVE_PART_NOT_FOUND]: 'mediaArchivePartNotFound',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_EMPTY]: 'mediaArchiveSelectionEmpty',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_TOO_LARGE]: 'mediaArchiveSelectionTooLarge',
    [ERROR_CODES.MEDIA_ARCHIVE_SELECTION_INVALID]: 'mediaArchiveSelectionInvalid',
    [ERROR_CODES.MEDIA_IMAGE_TOO_MANY_PIXELS]: 'mediaImageTooManyPixels',
    [ERROR_CODES.MEDIA_PROCESSING_BUSY]: 'mediaProcessingBusy',
    [ERROR_CODES.METHOD_NOT_ALLOWED]: 'methodNotAllowed',
    [ERROR_CODES.INVALID_PAID_SERVICE_KIND]: 'invalidPaidServiceKind',
    [ERROR_CODES.MODULE_NOT_AVAILABLE]: 'moduleUnavailable',
    [ERROR_CODES.ORDER_NOT_PENDING]: 'orderNotPending',
    [ERROR_CODES.ORDER_NOT_REFUNDABLE]: 'orderNotRefundable',
    [ERROR_CODES.PLAN_TIER_CURRENCY_MISMATCH]: 'planCurrencyMismatch',
    [ERROR_CODES.PLAN_TIER_CURRENCY_UNSUPPORTED]: 'planCurrencyUnsupported',
    [ERROR_CODES.PLAN_TIER_IN_USE]: 'planInUse',
    [ERROR_CODES.PLAN_TIER_IS_ONLY_DEFAULT]: 'planIsOnlyDefault',
    [ERROR_CODES.PLAN_TIER_NOT_AN_UPGRADE]: 'planNotAnUpgrade',
    [ERROR_CODES.PLAN_TIER_NOT_PRICED]: 'planNotPriced',
    [ERROR_CODES.PLAN_TIER_NOT_PURCHASABLE]: 'planNotPurchasable',
    [ERROR_CODES.PLAN_TIER_NOT_AVAILABLE_FOR_EVENT_TYPE]: 'planTierNotAvailableForEventType',
    [ERROR_CODES.POST_MEDIA_LIMIT_EXCEEDED]: 'postMediaLimitExceeded',
    [ERROR_CODES.PAID_SERVICE_CURRENCY_MISMATCH]: 'paidServiceCurrencyMismatch',
    [ERROR_CODES.PAID_SERVICE_IN_USE]: 'paidServiceInUse',
    [ERROR_CODES.PAID_SERVICE_NOT_ON_PLAN]: 'paidServiceNotOnPlan',
    [ERROR_CODES.PAID_SERVICE_NOT_PURCHASABLE]: 'paidServiceNotPurchasable',
    [ERROR_CODES.QR_LINK_NOT_FOUND]: 'qrLinkNotFound',
    [ERROR_CODES.RATE_LIMITED]: 'rateLimited',
    [ERROR_CODES.EVENT_SCHEDULE_LOCKED]: 'eventScheduleLocked',
    [ERROR_CODES.REFUND_ALREADY_REQUESTED]: 'refundAlreadyRequested',
    [ERROR_CODES.REFUND_NOT_ELIGIBLE]: 'refundNotEligible',
    [ERROR_CODES.REFUND_REQUEST_NOT_PENDING]: 'refundNotPending',
    [ERROR_CODES.REACTION_TYPE_IN_USE]: 'reactionTypeInUse',
    [ERROR_CODES.REACTION_TYPE_LIMIT_EXCEEDED]: 'reactionTypeLimitExceeded',
    [ERROR_CODES.REACTION_TYPE_NOT_USABLE]: 'reactionTypeNotUsable',
    [ERROR_CODES.RESOURCE_NOT_FOUND]: 'resourceNotFound',
    [ERROR_CODES.STORAGE_UPLOAD_FAILED]: 'storageUploadFailed',
    [ERROR_CODES.ORIGINALS_ADDON_NOT_ACTIVE]: 'originalsAddonNotActive',
    [ERROR_CODES.REQUEST_TOO_LARGE]: 'requestTooLarge',
    [ERROR_CODES.UNSUPPORTED_MEDIA_FORMAT]: 'unsupportedMediaFormat',
    [ERROR_CODES.TOO_MANY_FILES]: 'tooManyFiles',
    [ERROR_CODES.VALIDATION_FAILED]: 'validationFailed',
    [ERROR_CODES.INVALID_PLAN_TIER_SCOPE]: 'invalidPlanTierScope',
    [ERROR_CODES.WEBHOOK_ALREADY_PROCESSED]: 'webhookAlreadyProcessed',
    [ERROR_CODES.WEBHOOK_NOT_REPLAYABLE]: 'webhookNotReplayable',
    [ERROR_CODES.WEBHOOK_PAYLOAD_TOO_LARGE]: 'webhookPayloadTooLarge',
} satisfies Record<KnownApiErrorCode, ApiErrorMessageKey>;

export function getApiErrorMessageKey(code: number | string | undefined): ApiErrorMessageKey | undefined {
    return API_ERROR_MESSAGE_KEYS[code as KnownApiErrorCode];
}
