import { ApiError } from '@/lib/api/client';
import { ERROR_CODES, getErrorCode } from '@/lib/api/errors';
import type { EventModuleResponseDto, GalleryModuleConfiguration, QrLinkResolutionDto, QrLinkResponseDto } from '@/lib/api/types';
import { routes } from '@/lib/routes';

export type QrTerminalCopyKey = 'unknown' | 'revoked' | 'expired' | 'unavailable';

export function getQrTerminalCopyKey(resolution?: QrLinkResolutionDto | null, error?: unknown): QrTerminalCopyKey {
    if (error instanceof ApiError && (error.status === 404 || getErrorCode(error) === ERROR_CODES.QR_LINK_NOT_FOUND)) {
        return 'unknown';
    }

    if (resolution?.status === 'REVOKED') return 'revoked';
    if (resolution?.status === 'EXPIRED') return 'expired';
    if (resolution?.status === 'TARGET_UNAVAILABLE') return 'unavailable';
    return 'unknown';
}

// Where a scanned link that leads to an invitation sends the visitor, or null
// when the QR page renders something itself. The shared join link goes straight
// to sign-up for a newcomer, but a signed-in visitor goes to the invite page:
// /register would bounce them to /home and drop the invitation.
export function getQrRedirectPath(resolution: QrLinkResolutionDto | null | undefined, isAuthenticated: boolean): string | null {
    if (resolution?.status !== 'ACTIVE' || !resolution.inviteToken) return null;

    if (resolution.targetType === 'INVITATION') return routes.inviteToken(resolution.inviteToken);
    if (resolution.targetType === 'EVENT_JOIN') {
        return isAuthenticated ? routes.inviteToken(resolution.inviteToken) : routes.auth.register({ invite: resolution.inviteToken });
    }
    return null;
}

// The event's gallery upload QR code — whichever MEDIA_UPLOAD link hasn't been
// revoked, auto-generated or not. Not revoked (rather than strictly ACTIVE) so a
// link temporarily blocked by the qrUploadEnabled config flag (status
// TARGET_UNAVAILABLE) still surfaces instead of looking like it doesn't exist.
export function findGalleryQrLink(qrLinks: QrLinkResponseDto[]): QrLinkResponseDto | null {
    return qrLinks.find((link) => link.targetType === 'MEDIA_UPLOAD' && link.status !== 'REVOKED') ?? null;
}

export function hasGalleryQrLink(qrLinks: QrLinkResponseDto[]): boolean {
    return findGalleryQrLink(qrLinks) !== null;
}

// The auto-generated gallery QR can't be revoked or duplicated from the host UI
// — see docs/integration guides/default-qr-links-fe-integration.md. This is a
// frontend-only guardrail; the backend still technically allows both actions.
export function isHostManagedQrLink(qrLink: QrLinkResponseDto): boolean {
    return qrLink.autoGenerated;
}

// Whether the gallery QR feature (the upload link itself, any nav entry
// pointing at it, and its dedicated page) should exist at all for this event:
// the gallery module must be available, and the plan's qrUploadEnabled config
// flag must be true (a missing key counts as off). Without both, the backend
// mints no MEDIA_UPLOAD link. See gallery-qr-link-plan-gating-fe-integration.md.
export function isGalleryQrFeatureEnabled(modules: EventModuleResponseDto[] | undefined): boolean {
    const galleryModule = modules?.find((module_) => module_.moduleKey === 'gallery');
    if (!galleryModule?.isAvailable) return false;

    const configuration = galleryModule.configuration as GalleryModuleConfiguration | null;
    return configuration?.qrUploadEnabled === true;
}

// Whether this event's members (not only hosts) get the gallery's prebuilt archive after it ends.
// The backend decides access; this only decides whether to offer it.
export function isMemberArchiveEnabled(modules: EventModuleResponseDto[] | undefined): boolean {
    const galleryModule = modules?.find((module_) => module_.moduleKey === 'gallery');
    if (!galleryModule?.isAvailable) return false;

    const configuration = galleryModule.configuration as GalleryModuleConfiguration | null;
    return configuration?.memberArchiveAfterEnd === true;
}
