import { ApiError } from '@/lib/api/client';
import { ERROR_CODES, getErrorCode } from '@/lib/api/errors';
import type { EventModuleResponseDto, GalleryModuleConfiguration, QrLinkResolutionDto, QrLinkResponseDto } from '@/lib/api/types';

export type QrTerminalCopyKey = 'unknown' | 'revoked' | 'expired' | 'unavailable';

export function getQrTerminalCopyKey(resolution?: QrLinkResolutionDto | null, error?: unknown): QrTerminalCopyKey {
    if (error instanceof ApiError && (error.status === 404 || getErrorCode(error) === ERROR_CODES.QR_LINK_NOT_FOUND)) {
        return 'unknown';
    }

    if (resolution?.status === 'REVOKED') return 'revoked';
    if (resolution?.status === 'EXPIRED') return 'expired';
    if (resolution?.status === 'TARGET_UNAVAILABLE') return 'unavailable';
    return 'unknown';
}

// The event's gallery upload QR code — whichever MEDIA_UPLOAD link hasn't been
// revoked, auto-generated or not. Not revoked (rather than strictly ACTIVE) so a
// link temporarily blocked by the qrUploadEnabled config flag (status
// TARGET_UNAVAILABLE) still surfaces instead of looking like it doesn't exist.
export function findGalleryQrLink(qrLinks: QrLinkResponseDto[]): QrLinkResponseDto | null {
    return qrLinks.find((link) => link.targetType === 'MEDIA_UPLOAD' && link.status !== 'REVOKED') ?? null;
}

export function hasGalleryQrLink(qrLinks: QrLinkResponseDto[]): boolean {
    return findGalleryQrLink(qrLinks) !== null;
}

// The auto-generated gallery QR can't be revoked or duplicated from the host UI
// — see docs/integration guides/default-qr-links-fe-integration.md. This is a
// frontend-only guardrail; the backend still technically allows both actions.
export function isLockedGalleryQrLink(qrLink: QrLinkResponseDto): boolean {
    return qrLink.targetType === 'MEDIA_UPLOAD' && qrLink.autoGenerated;
}

// Whether the gallery QR feature (the upload link itself, any nav entry
// pointing at it, and its dedicated page) should exist at all for this event:
// the gallery module must be available, and the event type's own
// qrUploadEnabled config flag — a plan/event-type setting, not something a
// host toggles — must be on. See
// event-type-feature-toggles-quotas-fe-integration.md §2.
export function isGalleryQrFeatureEnabled(modules: EventModuleResponseDto[] | undefined): boolean {
    const galleryModule = modules?.find((module_) => module_.moduleKey === 'gallery');
    if (!galleryModule?.isAvailable) return false;

    const configuration = galleryModule.configuration as GalleryModuleConfiguration | null;
    return configuration?.qrUploadEnabled ?? true;
}
